apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: test
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: 80
Type: NodePort